### ISSUE TITLE
Fix Jinput setup

### ISSUE THREAD

**Issue by QuickRecon** [QuickRecon/ScotchOARKit#15]
Something is very wrong with the way Jinput is setup and I don't know enough about the java directory structures to fix it. The exception I'm getting is this:

Exception in thread "main" java.lang.NoClassDefFoundError: net/java/games/util/plugins/Plugins
    at net.java.games.input.ControllerEnvironment.<clinit>(ControllerEnvironment.java:84)
    at com.scotch.OARKit.java.helpers.JInputJoystick.initController(JInputJoystick.java:81)
    at com.scotch.OARKit.java.helpers.JInputJoystick.<init>(JInputJoystick.java:65)
    at com.scotch.OARKit.java.helpers.gamepad.gamepad(gamepad.java:22)
    at com.scotch.OARKit.java.Main.main(Main.java:49)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: net.java.games.util.plugins.Plugins
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 10 more

I have looked into the error and it looks like this may be the fix but I don't know how to implement it: http://www.java-gaming.org/index.php?topic=2076.0

**Comment by Whoa-exclamation-mark** [comment]
Can you commit the new gamepad class?

**Comment by QuickRecon** [comment]
getting different error:

Mar 18, 2016 8:50:15 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to load library: no jinput-linux64 in java.library.path

java.lang.UnsatisfiedLinkError: no jinput-linux64 in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at net.java.games.input.LinuxEnvironmentPlugin$1.run(LinuxEnvironmentPlugin.java:69)
    at java.security.AccessController.doPrivileged(Native Method)
    at net.java.games.input.LinuxEnvironmentPlugin.loadLibrary(LinuxEnvironmentPlugin.java:61)
    at net.java.games.input.LinuxEnvironmentPlugin.<clinit>(LinuxEnvironmentPlugin.java:104)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:159)
    at com.scotch.OARKit.java.helpers.JInputJoystick.initController(JInputJoystick.java:81)
    at com.scotch.OARKit.java.helpers.JInputJoystick.<init>(JInputJoystick.java:65)
    at com.scotch.OARKit.java.helpers.gamepad.gamepad(gamepad.java:22)
    at com.scotch.OARKit.java.Main.main(Main.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Mar 18, 2016 8:50:15 PM net.java.games.input.ControllerEnvironment log
INFO: net.java.games.input.LinuxEnvironmentPlugin is not supported

**Comment by Whoa-exclamation-mark** [comment]
Under Java change all the Linux libs to have no lib in front

**Comment by Whoa-exclamation-mark** [comment]
Linux support is not working for fat jar. Will fix with ANT

**Comment by QuickRecon** [comment]
just made the change, no luck

**Comment by Whoa-exclamation-mark** [comment]
Can you post the **whole** log

**Comment by QuickRecon** [comment]
/usr/lib/jvm/java-8-jdk/bin/java -Didea.launcher.port=7534 -Didea.launcher.bin.path=/usr/share/intellij-idea-ultimate-edition/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-jdk/jre/lib/charsets.jar:/usr/lib/jvm/java-8-jdk/jre/lib/deploy.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-jdk/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-jdk/jre/lib/javaws.jar:/usr/lib/jvm/java-8-jdk/jre/lib/jce.jar:/usr/lib/jvm/java-8-jdk/jre/lib/jfr.jar:/usr/lib/jvm/java-8-jdk/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-jdk/jre/lib/jsse.jar:/usr/lib/jvm/java-8-jdk/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-jdk/jre/lib/plugin.jar:/usr/lib/jvm/java-8-jdk/jre/lib/resources.jar:/usr/lib/jvm/java-8-jdk/jre/lib/rt.jar:/home/aren/Documents/Code/ScotchOARKit/target/classes:/home/aren/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar:/home/aren/.m2/repository/net/java/jinput/jinput/2.0.6/jinput-2.0.6.jar:/home/aren/Documents/Code/ScotchOARKit/lib/jutils-1.0.0.jar:/usr/share/intellij-idea-ultimate-edition/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain com.scotch.OARKit.java.Main
Linux
/tmp/jinput-linux.so
/tmp/jinput-linux64.so
Mar 18, 2016 8:54:19 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to load library: no jinput-linux64 in java.library.path

java.lang.UnsatisfiedLinkError: no jinput-linux64 in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at net.java.games.input.LinuxEnvironmentPlugin$1.run(LinuxEnvironmentPlugin.java:69)
    at java.security.AccessController.doPrivileged(Native Method)
    at net.java.games.input.LinuxEnvironmentPlugin.loadLibrary(LinuxEnvironmentPlugin.java:61)
    at net.java.games.input.LinuxEnvironmentPlugin.<clinit>(LinuxEnvironmentPlugin.java:104)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:159)
    at com.scotch.OARKit.java.helpers.JInputJoystick.initController(JInputJoystick.java:81)
    at com.scotch.OARKit.java.helpers.JInputJoystick.<init>(JInputJoystick.java:65)
    at com.scotch.OARKit.java.helpers.gamepad.gamepad(gamepad.java:22)
    at com.scotch.OARKit.java.Main.main(Main.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
No controller found!
Controller found
This controller has 0 buttons
Mar 18, 2016 8:54:19 PM net.java.games.input.ControllerEnvironment log
INFO: net.java.games.input.LinuxEnvironmentPlugin is not supported

Problem Connecting to Local Host - Is the server up?
Please Specify Your Own IP
Inside Dev Enviroment
Quitting Application
Problem Closing Socket - Is the server still up?

Process finished with exit code 0

**Comment by Whoa-exclamation-mark** [comment]
After startLibraries can you put System.out.println(System.getProperty("java.library.path")); and post the result

**Comment by Whoa-exclamation-mark** [comment]
Also try downloading java-32 bit there is some issues with 64 in LWJGL I have encountered and JInput may have been the issue

**Comment by QuickRecon** [comment]
the output was /tmp

**Comment by Whoa-exclamation-mark** [comment]
OK so every thing is working how it should. I think it is a issue with JInput it self. The 32 bit is more stable - download 32 bit java and in project settings set a new Project SDK to be Java 32bit

**Comment by QuickRecon** [comment]
doing that now

**Comment by QuickRecon** [comment]
still not working:

Mar 18, 2016 9:13:55 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to load library: no jinput-linux in java.library.path

java.lang.UnsatisfiedLinkError: no jinput-linux in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at net.java.games.input.LinuxEnvironmentPlugin$1.run(LinuxEnvironmentPlugin.java:69)
    at java.security.AccessController.doPrivileged(Native Method)
    at net.java.games.input.LinuxEnvironmentPlugin.loadLibrary(LinuxEnvironmentPlugin.java:61)
    at net.java.games.input.LinuxEnvironmentPlugin.<clinit>(LinuxEnvironmentPlugin.java:102)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:159)
    at com.scotch.OARKit.java.helpers.JInputJoystick.initController(JInputJoystick.java:81)
    at com.scotch.OARKit.java.helpers.JInputJoystick.<init>(JInputJoystick.java:65)
    at com.scotch.OARKit.java.helpers.gamepad.gamepad(gamepad.java:22)
    at com.scotch.OARKit.java.Main.main(Main.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Mar 18, 2016 9:13:55 PM net.java.games.input.ControllerEnvironment log
INFO: net.java.games.input.LinuxEnvironmentPlugin is not supported

Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
    at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:217)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)

Process finished with exit code 1

**Comment by Whoa-exclamation-mark** [comment]
Firstly it looks like you have Java 7 or something that does not have Java fx. I would just recommend developing on the Mac and I will spin up a VM tomorrow and track down the issue

**Comment by QuickRecon** [comment]
I checked on mac but it is not detecting the gamepad: 

Mac OS X
/var/folders/wy/tbzyygws31v287f3bj5j_hdjlv9gzv/T/libjinput-osx.jnilib
No controller found!
Controller found
This controller has 0 buttons
Starting Server on Local Host
Inside Dev Enviroment
Quitting Application

Process finished with exit code 0

**Comment by QuickRecon** [comment]
Looks like it may be an issue with my gamepad.

**Comment by QuickRecon** [comment]
Gamepad is working. Just need linux support.
