### ISSUE TITLE
Using JInput for input with xBox controller 

### ISSUE THREAD

**Issue by Whoa-exclamation-mark** [QuickRecon/ScotchOARKit#4]
Hi All,

The next thing that we have to do in the project is start on JInput for the xBox thing. Post any **USE FULL** links that you have found that may help. Also if you are updating from a couple of days ago please run a full build via Maven or your project will not work.

**Comment by Whoa-exclamation-mark** [comment]
I have found a older tutorial but still very valid:
https://theuzo007.wordpress.com/2012/09/02/joystick-in-java-with-jinput/
Here is also a Uni thing also:
http://fivedots.coe.psu.ac.th/~ad/jg2/ch11/GamePadIntro.pdf

**Comment by QuickRecon** [comment]
I have looked into the documentation but the import statements don't work.

**Comment by QuickRecon** [comment]
Am currently getting this exception:

Exception in thread "main" java.lang.NoClassDefFoundError: net/java/games/util/plugins/Plugins
    at net.java.games.input.ControllerEnvironment.<clinit>(ControllerEnvironment.java:84)
    at com.scotch.OARKit.java.helpers.JInputJoystick.initController(JInputJoystick.java:81)
    at com.scotch.OARKit.java.helpers.JInputJoystick.<init>(JInputJoystick.java:65)
    at com.scotch.OARKit.java.helpers.gamepad.gamepad(gamepad.java:23)
    at com.scotch.OARKit.java.Main.main(Main.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: net.java.games.util.plugins.Plugins
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 10 more

Any ideas?

**Comment by QuickRecon** [comment]
this link looks promising: http://yaolddawg.blogspot.com.au/2011/08/configure-open-source-controller-jinput.html for configureation on mac and linux, but it involves extracting the jar to a directory, will this break maven?

**Comment by QuickRecon** [comment]
Linux support removed, jinput working
